[package]
name = "viewlake"
version = "0.1.0"
edition = "2024"

[dependencies]
widestring = "1.2.0"
windows = { version = "0.52", features = ["Win32_Networking_WinHttp",
    "Win32_Foundation",
    "Win32_System_SystemInformation",
    "Wdk_System_SystemServices",
    "Win32_System_SystemServices",
    "Win32_NetworkManagement_NetManagement",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper"] }


[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true

[features]
logging = []
