[target.x86_64-pc-windows-gnu]
rustflags = [
  "-Z", "location-detail=none",
  "-Z", "fmt-debug=none",
]

[target.x86_64-pc-windows-msvc]
rustflags = [
  "-Z", "location-detail=none",
  "-Z", "fmt-debug=none",
]

